### ISSUE TITLE
hello thanks, get error .. 

### ISSUE THREAD

**Issue by GreenAA** [RevoltSecurities/GoogleDorker#1]
json returned "Request contains an invalid argument.". Details: "[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]">

**Comment by RevoltSecurities** [comment]
Hello @GreenAA ,
Please send a screenshot that contains the following error so I can 
check and resolve it

**Comment by GreenAA** [comment]
![Uploading Screenshot 2024-04-06 171759.png…]()

**Comment by GreenAA** [comment]
![Screenshot 2024-04-06 171759](https://github.com/sanjai-AK47/GoogleDorker/assets/87846163/1bc19edc-6063-430f-beea-9bd9b51ed5a0)

**Comment by GreenAA** [comment]
i try 

method 1 / 2 
dorker -q "inurl:api site:bentley.com" --output google_dorks.txt
dorker -d bentley.com -q inurl:api -o google_dorks.txt

**Comment by RevoltSecurities** [comment]
Hello @GreenAA ,
I have tried the same request and dorks with my api keys and configs and I got results for that also, I think possibly you api usage is exhausted for today thats why it causing this error because from my side I can't reproduce this error with command given by you and instead I got some results and you can see those results from the attachements
![dorker1](https://github.com/sanjai-AK47/GoogleDorker/assets/119435129/9c63488e-567a-4077-9f21-a7b771ec4760)
![dorker2](https://github.com/sanjai-AK47/GoogleDorker/assets/119435129/92c2116f-8bc1-4515-851a-3d3251753a08)

please try again the same dork tomorrow and if you are getting the same error I will reinvestigate and will make a update
on google dorker tool :)

kind regards,
@sanjai-AK47

**Comment by GreenAA** [comment]
thanks bro

**Comment by GreenAA** [comment]
bro now is working , thanks for all .. working.
